#!/usr/bin/env python3
"""Generate remaining Voidborne Command audio assets via FAL + post-process.
SFX already regenerated by previous run. This handles Music (3) + Voice (6).
Uses ffmpeg for WAV→OGG conversion (libsndfile OGG encoder segfaults on large files).
Run with: python3 -u tools/generate_remaining_audio.py
"""

import os
import sys
import time
import tempfile
import subprocess
import urllib.request
from pathlib import Path

import numpy as np
import soundfile as sf

FAL_KEY = os.environ.get("FAL_KEY", "")
if not FAL_KEY:
    env_path = Path.home() / ".hermes/profiles/coder/.env"
    for line in env_path.read_text().splitlines():
        if line.startswith("FAL_KEY="):
            FAL_KEY = line.split("=", 1)[1].strip()
            break
if not FAL_KEY:
    print("ERROR: FAL_KEY not found", flush=True)
    sys.exit(1)
os.environ["FAL_KEY"] = FAL_KEY

import fal_client

REPO = Path("/home/ganomix/projects/voidborne-command/.worktrees/t_08774a2f")
AUDIO_DIR = REPO / "assets/audio"
SOURCES_PATH = REPO / "docs/SOURCES.md"

MUSIC_ASSETS = [
    ("music/combat.ogg",       "Driving aggressive electronic combat music, pounding percussion, dark synth bass, 90 BPM, D minor, instrumental, sci-fi space battle", 60),
    ("music/exploration.ogg",  "Calm ambient sci-fi exploration music, ethereal pads, distant signals, 90 BPM, D minor, instrumental, space travel", 60),
    ("music/station.ogg",     "Neutral industrial station music, commercial dock feel, mechanical rhythm, 90 BPM, D minor, instrumental, space station", 60),
]

VOICE_ASSETS = [
    ("voice/commander_battle_stations.ogg", "Battle stations. All hands to combat readiness.", "pz6K7Jcl0q7g1Twn5B0p", "Marcus - authoritative male commander"),
    ("voice/commander_engage.ogg",          "Engaging hostiles. Weapons free.",                   "pz6K7Jcl0q7g1Twn5B0p", "Marcus - authoritative male commander"),
    ("voice/marine_contact.ogg",            "Contact! Boarding party inbound!",                    "pz6K7Jcl0q7g1Twn5B0p", "Marcus - authoritative male marine"),
    ("voice/marine_affirmative.ogg",        "Affirmative. Moving to position.",                    "pz6K7Jcl0q7g1Twn5B0p", "Marcus - authoritative male marine"),
    ("voice/announcer_docking.ogg",         "Docking clearance granted. Welcome to the station.",  "jsSMF9q1HO2Qzh0HR8hn", "Charlotte - professional female announcer"),
    ("voice/announcer_welcome.ogg",         "Welcome aboard, Commander. Shipyard services are available.", "jsSMF9q1HO2Qzh0HR8hn", "Charlotte - professional female announcer"),
]

SFX_ASSETS = [
    ("sfx/laser.ogg",           "Sci-fi energy cannon fire, short punchy laser blast, cold clean military, 1 second", 2),
    ("sfx/beam.ogg",            "Sustained sci-fi beam weapon hum, energy weapon buzz, continuous fire, cold clean", 2),
    ("sfx/hit.ogg",             "Metallic hull impact thud, spaceship armor hit, physical weighty, debris rattle", 2),
    ("sfx/shield.ogg",          "Energy shield absorption bloom, clean electronic force field, sci-fi defensive", 2),
    ("sfx/explosion.ogg",      "Deep spaceship explosion, rumbling sub-bas, debris shockwave, cinematic", 3),
    ("sfx/disabled.ogg",       "Subsystem failure warning tone, descending electronic alarm, ship disabled", 2),
    ("sfx/subsystem_hit.ogg",  "Sharp targeted subsystem damage, electronic component failure, precise", 2),
    ("sfx/engine_hit.ogg",     "Engine damage rattle, mechanical distress, metal grinding, spaceship engine", 2),
    ("sfx/weapon_overheat.ogg","Dry mechanical overheat click, weapon system failure, short metallic", 2),
    ("sfx/hull_alarm.ogg",     "Urgent low hull warning klaxon, repeating-capable alarm, military sci-fi", 2),
    ("sfx/mining_hit.ogg",     "Asteroid mining impact chip, rocky brittle debris, short crunch", 2),
    ("sfx/asteroid_break.ogg", "Asteroid destruction crumble, satisfying rock fragmentation, space mining", 3),
    ("sfx/board.ogg",          "Airlock breach opening, marine deployment, pressurized hatch release", 2),
    ("sfx/boarding_round.ogg", "Brief firefight impact exchange, short combat burst, boarding action", 2),
    ("sfx/boarding_fail.ogg",  "Mission failure retreat tone, defeat alarm, descending military", 2),
    ("sfx/capture.ogg",        "Victory faction-switch fanfare, rising major interval, triumphant short", 2),
    ("sfx/ui_recruit.ogg",     "Positive UI confirmation chime, crew hired success, clean electronic", 1),
    ("sfx/ui_buy.ogg",         "Transaction purchase chime, commercial sci-fi, clean electronic", 1),
    ("sfx/ui_deny.ogg",        "Error denied buzzer, UI rejection, short electronic negative", 1),
    ("sfx/thruster.ogg",       "Engine thrust noise, spaceship main drive, low rumble, one-shot", 2),
    ("sfx/ambient.ogg",        "Space drone background hum, deep ambient void, seamless looping, 5 seconds", 5),
]

def call_stable_audio_25(prompt, seconds_total):
    result = fal_client.submit("fal-ai/stable-audio-25/text-to-audio", arguments={"prompt": prompt, "seconds_total": seconds_total}).get()
    url = result.get("audio", {}).get("url")
    if not url:
        raise RuntimeError(f"stable-audio-25: no audio url: {result}")
    return url

def call_elevenlabs_tts(text, voice_id):
    result = fal_client.submit("fal-ai/elevenlabs/tts/turbo-v2.5", arguments={"text": text, "voice_id": voice_id}).get()
    url = result.get("audio", {}).get("url")
    if not url:
        raise RuntimeError(f"elevenlabs: no audio url: {result}")
    return url

def download(url, suffix=".wav"):
    tmp = tempfile.NamedTemporaryFile(suffix=suffix, delete=False)
    tmp_path = tmp.name
    tmp.close()
    urllib.request.urlretrieve(url, tmp_path)
    return tmp_path

def wav_to_ogg(wav_path, ogg_path, vorbis_quality=4):
    """Convert WAV to OGG Vorbis via ffmpeg (avoids libsndfile segfault)."""
    subprocess.run(
        ["ffmpeg", "-y", "-i", wav_path, "-c:a", "libvorbis", "-q:a", str(vorbis_quality), str(ogg_path)],
        capture_output=True, check=True
    )

def postprocess_music(wav_path, out_ogg):
    data, rate = sf.read(wav_path, dtype="float32")
    peak = np.max(np.abs(data))
    if peak > 0:
        data = data * (0.6 / peak)
    # Write intermediate normalized WAV, then ffmpeg to OGG
    norm_wav = wav_path + ".norm.wav"
    sf.write(norm_wav, data, rate, format="WAV")
    out_ogg.parent.mkdir(parents=True, exist_ok=True)
    wav_to_ogg(norm_wav, out_ogg)
    os.unlink(norm_wav)
    dur = len(data) / rate
    ch = 2 if data.ndim > 1 else 1
    print(f"  OK: {out_ogg.name} ({dur:.1f}s, {ch}ch, peak 0.6)", flush=True)

def postprocess_voice(input_path, out_ogg, is_mp3=False):
    """Post-process voice: if MP3, convert via ffmpeg; then mono + normalize."""
    if is_mp3:
        wav_path = input_path + ".wav"
        subprocess.run(["ffmpeg", "-y", "-i", input_path, wav_path], capture_output=True, check=True)
    else:
        wav_path = input_path

    data, rate = sf.read(wav_path, dtype="float32")
    if data.ndim > 1:
        data = np.mean(data, axis=1)
    peak = np.max(np.abs(data))
    if peak > 0:
        data = data * (0.8 / peak)
    # Write normalized WAV, then ffmpeg to OGG
    norm_wav = wav_path + ".norm.wav"
    sf.write(norm_wav, data, rate, format="WAV")
    out_ogg.parent.mkdir(parents=True, exist_ok=True)
    wav_to_ogg(norm_wav, out_ogg)
    os.unlink(norm_wav)
    print(f"  OK: {out_ogg.name} ({len(data)/rate:.2f}s, mono, peak 0.8)", flush=True)

    # Cleanup
    if is_mp3 and os.path.exists(wav_path):
        os.unlink(wav_path)

def main():
    sources = []

    # ── Music ───────────────────────────────────────────────────────
    print(f"\n=== MUSIC: {len(MUSIC_ASSETS)} assets via fal-ai/stable-audio-25 ===", flush=True)
    for i, (rel_path, prompt, secs) in enumerate(MUSIC_ASSETS):
        out_ogg = AUDIO_DIR / rel_path
        print(f"[{i+1}/3] {rel_path}: \"{prompt[:60]}...\" ({secs}s)", flush=True)
        wav_tmp = None
        try:
            url = call_stable_audio_25(prompt, secs)
            wav_tmp = download(url, suffix=".wav")
            postprocess_music(wav_tmp, out_ogg)
            sources.append(("Music", rel_path, "fal-ai/stable-audio-25/text-to-audio", prompt))
        except Exception as e:
            print(f"  FAIL: {e}", flush=True)
            import traceback; traceback.print_exc()
        finally:
            if wav_tmp and os.path.exists(wav_tmp):
                os.unlink(wav_tmp)
        time.sleep(1)

    # ── Voice ───────────────────────────────────────────────────────
    print(f"\n=== VOICE: {len(VOICE_ASSETS)} assets via fal-ai/elevenlabs/tts/turbo-v2.5 ===", flush=True)
    for i, (rel_path, text, voice_id, voice_desc) in enumerate(VOICE_ASSETS):
        out_ogg = AUDIO_DIR / rel_path
        print(f"[{i+1}/6] {rel_path}: \"{text}\"", flush=True)
        mp3_tmp = None
        try:
            url = call_elevenlabs_tts(text, voice_id)
            # ElevenLabs returns MP3
            mp3_tmp = download(url, suffix=".mp3")
            postprocess_voice(mp3_tmp, out_ogg, is_mp3=True)
            sources.append(("Voice", rel_path, "fal-ai/elevenlabs/tts/turbo-v2.5", f'text="{text}", voice={voice_desc}'))
        except Exception as e:
            print(f"  FAIL: {e}", flush=True)
            import traceback; traceback.print_exc()
        finally:
            if mp3_tmp and os.path.exists(mp3_tmp):
                os.unlink(mp3_tmp)
        time.sleep(0.5)

    # ── Add existing SFX to sources (already FAL-generated) ─────────
    for rel_path, prompt, secs in SFX_ASSETS:
        sources.append(("SFX", rel_path, "fal-ai/stable-audio", prompt))

    # ── Write SOURCES.md ────────────────────────────────────────────
    print(f"\n=== Writing docs/SOURCES.md ===", flush=True)
    SOURCES_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(SOURCES_PATH, "w") as f:
        f.write("# Audio Asset Sources\n\n")
        f.write("Provenance for all 30 audio assets in Voidborne Command.\n")
        f.write("Generated via FAL.ai endpoints and post-processed (mono/normalize/trim → OGG Vorbis).\n\n")
        for cat in ["SFX", "Music", "Voice"]:
            items = [s for s in sources if s[0] == cat]
            if not items:
                continue
            f.write(f"## {cat}\n\n")
            f.write("| File | Endpoint | Prompt |\n")
            f.write("|------|----------|--------|\n")
            for _, rel_path, endpoint, prompt_text in items:
                f.write(f"| `{rel_path}` | `{endpoint}` | {prompt_text} |\n")
            f.write("\n")
    print(f"Wrote {SOURCES_PATH}", flush=True)

    # ── Verify all 30 ──────────────────────────────────────────────
    print(f"\n=== Verification ===", flush=True)
    all_ogg = list(AUDIO_DIR.glob("sfx/*.ogg")) + list(AUDIO_DIR.glob("music/*.ogg")) + list(AUDIO_DIR.glob("voice/*.ogg"))
    ok = bad = 0
    for ogg in sorted(all_ogg):
        try:
            data, rate = sf.read(str(ogg))
            size = ogg.stat().st_size
            if size > 0 and len(data) > 0:
                ok += 1
            else:
                print(f"  BAD: {ogg} (empty)", flush=True); bad += 1
        except Exception as e:
            print(f"  BAD: {ogg} ({e})", flush=True); bad += 1
    print(f"Result: {ok} OK, {bad} BAD out of {len(all_ogg)}", flush=True)
    if ok >= 30:
        print("SUCCESS!", flush=True)
    else:
        print(f"INCOMPLETE: only {ok}/30 OK", flush=True)

if __name__ == "__main__":
    main()
